config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :links do
    collection do
      get 'my-links', to: "links#my_links", as: :my
      get 'my-approved-links', to: "links#my_approved_links",
          as: :my_approved
    end
    
    member do
      post 'approve-link', to: "links#approve_link", as: "approve"
      delete 'unapprove-link', to: "links#unapprove_link", as: "unapprove"
      get 'show-approvers', to: "links#show_approvers", as: "show_approvers"
    end
    
    resources :comments, only: [:create, :destroy]
  end
  
  resources :user, only: [:show] do
    member do
      get 'submitted-links', to: "user#submitted_links", as: "submitted_links"
      get 'approved-links', to: "user#approved_links", as: "approved_links"
    end
  end
  
  root to: "links#index"
  
  get 'about' => 'pages#about', as: :about
end

app/models/link.rb
class Link < ApplicationRecord
  has_attached_file :website_image,
    styles: { medium: "200x200#", thumb: "100x100#" },
    storage: :cloudinary,
    default_url: "/images/missing.png",
    path: ":id/:style/:filename",
    cloudinary_upload_options: {
      default: { tags: "web_images" }
    }

      
  # Validations
  validates_attachment_content_type :website_image, content_type: /\Aimage\/.*\z/
  validates :url, uniqueness: true
  validates_presence_of :url, :title, :description
  
  # Associations
  belongs_to :user
  
  has_many :approvals
  has_many :approvers, through: :approvals, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  
  
  def get_link_data(url)
    url = format_url_correctly(url)
    if Link.where(url: url).any?
      self.errors.add(:url, "Link already exists.")
      return false  
    end
    
    begin
      return LinkThumbnailer.generate(url)
    rescue
      self.errors.add(:url, "Unable to reach link.")
      return false
    end
    
    url
  end
  
  def fetch_website_image(link_data)
    unless link_data.images.empty?
      begin
        image_url = link_data.images.first.src.to_s
        image_url = remove_query_string(image_url)
        image = open(image_url)
        filename = image.base_uri.to_s.split('/')[-1]
        image_path = Rails.root.join('tmp', filename)   
        IO.copy_stream(image, image_path)
        File.open(image_path, 'rb') do |file|
          self.website_image = file
        end
      rescue OpenURI::HTTPError
        logger.debug "Error fetching #{image_url} OpenURI::HTTPError"
      rescue
        logger.debug "Error fetching #{image_url}"
      end
    end
  end
  
  private
  
  def format_url_correctly(url)
    self.url = url
    unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
      self.url = "http://#{self.url}"
    end
    
    self.url
  end
  
  def remove_query_string(url)
    url.split('?').first
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :show_approvers]
  before_action :find_link, only: [:show, :edit, :update, :destroy,
    :approve_link, :unapprove_link, :show_approvers]
  before_action :set_ransack_search_object
  
  authorize_resource
  skip_authorize_resource only: [:my_links, :my_approved_links,
                                 :approve_link, :unapprove_link,
                                 :show_approvers]
  
  LinksPerPage = 10
    
  def index
    if params[:search_btn]
      @links = @q.result(distinct: true).order(created_at: :desc)
                 .paginate(:page => params[:page], :per_page => LinksPerPage)
    else
      @links = Link.order(created_at: :desc)
                   .paginate(:page => params[:page], :per_page => LinksPerPage)
    end
  end
  
  def my_links
    @links = Link.where(user: current_user).order(created_at: :desc)
                 .paginate(:page => params[:page], :per_page => LinksPerPage)
    render 'index'
  end
  
  def my_approved_links
    @links = current_user.approved_links.order(created_at: :desc)
                 .paginate(:page => params[:page], :per_page => LinksPerPage)
    render 'index'
  end
  
  def new
    @link = Link.new
  end
  
  def create
    respond_to do |format|
      format.js do
        @link = Link.new
        
        link_data = @link.get_link_data(link_params[:url])
        unless link_data
          render 'url_error' and return  # url_error.js.erb
        end
        @link.url = link_data.url
        
        if params[:fetch_url]  # first step: fetch url data
          @link.title = link_data.title
          @link.description = link_data.description
        elsif params[:add_link]  # second step: actual record creation
          @link.fetch_website_image(link_data)
          @link.title = link_params[:title]
          @link.description = link_params[:description]
          @link.user = current_user
          
          # image spoofing detection workaround
          # just set website_image_file_name to false
          if @link.errors[:website_image].first =~
             /has contents that are not what they are reported to be/
            @link.website_image_file_name = false
          end
          
          if @link.save
            redirect_to @link
          else
            render 'create' # create.js.erb
          end
        end
        
      end # format
    end # respont_to
  end
  
  def show
    @comments = @link.comments.includes(:user)
  end
  
  def approve_link
    respond_to do |format|
      format.js do
        begin 
          @link.approvers << current_user
        ensure
          render 'approve_link'
        end
      end
    end
  end
  
  def unapprove_link
    respond_to do |format|
      format.js do
        begin
          @link.approvers.delete(current_user)
        ensure
          render 'approve_link'
        end
      end
    end
  end
  
  def show_approvers
    respond_to do |format|
      format.js do
        @approvers = @link.approvers
        
        # render show_approvers.js.erb
      end
    end
  end
  
  def edit
  end
  
  def update
    if @link.update(title: link_params[:title], 
         description: link_params[:description])
      redirect_to @link
    else
      render 'show'
    end
  end
  
  def destroy
    @link.destroy
    redirect_to root_path
  end
  
  private
  
  def set_ransack_search_object
    @q = Link.ransack(params[:q])
  end
  
  def find_link
    @link = Link.find(params[:id])
  end
  
  def link_params
    params.require(:link).permit(:url, :title, :description, :website_image)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/partials/_approve_link.html.erb
<% if user_signed_in? %>
  <% if current_user.approved_links.include?(link) %>
    <%= link_to approval_display_text, unapprove_link_path(link),
                method: :delete, class: "btn btn-success", remote: true %>
  <% else %>
    <%= link_to approval_display_text, approve_link_path(link),
                method: :post, class: "btn btn-default", remote: true %>
  <% end %>
<% end %>

<%= link_to show_approvers_link_path(link), remote: true,
      class: "button-approve", "data-toggle": "modal",
      "data-target": "#approvers-modal" do %>
  <span class="badge">
    <%= pluralize(link.approvers.size, "Approver") %>
  </span>
<% end %>

<div id="approvers-modal" class="modal fade" tabindex="-1" role="dialog">
</div>

app/views/links/partials/_create_form_errors.html.erb
<div>
  <% if link.errors.any? %>
    <h4 class="text-danger"><%= pluralize(link.errors.size, "error") %>
        prevented this link from being saved.
    </h4>
    <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><span class="text-danger"><%= message %></span></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/links/partials/_create_form_plus.html.erb
<%= form_for(@link, remote: true, html: { class: "form-horizontal" }) do |f| %>
  <%= render partial: 'links/partials/create_form_errors',
             locals: { link: @link } %>

  <div class="form-group">
    <%= f.label :url, class: "control-label col-sm-1", for: "link_url" %>
    <div class="col-sm-6">
      <%= f.text_field :url, class: "form-control", readonly: true %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-1", for: "link_url" %>
    <div class="col-sm-6">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
    
  <div class="form-group">
    <%= f.label :description, class: "control-label col-sm-1", for: "link_url" %>
    <div class="col-sm-6">
      <%= f.text_area:description, size: "10x5", class: "form-control" %>
    </div>
  </div>
    
  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-6">
      <%= f.button "Add Link", class: "btn btn-success btn-lg",
            name: "add_link", data: { disable_with: adding_link_text } %>
    </div>
  </div>
  
<% end %>

app/views/links/partials/_create_url_errors.html.erb
<% if @link.errors.any? %>
  <% @link.errors.messages.each do |k, messages| %>
    <% messages.each do |message| %>
      <h3 class="col-sm-offset-1"><span class="text-danger">
        <%= message %></span></h3>
    <% end %>
  <% end %>
<% end %>

app/views/links/partials/_link.html.erb
<div class="row">
  <div class="col-sm-8 col-xs-12">
    
    <div class="panel panel-default link-featured">
      <div class="panel-heading">
        <h2 class="link-title"><%= link.title %></h2>
      </div>
      
      <div class="panel-body">
        <p class="text-center">
          <%= link_to link.url, target: "_blank" do %>
            <%= image_tag(link.website_image.url(:medium), size: "200x200") %>   
          <% end %>
        </p>
      </div>
      
      <ul class="list-group">
        <li class="list-group-item link-options">
          <div class="link-options-group">
            <span id="link-approval">
              <%= render partial: 'links/partials/approve_link', 
                         locals: { link: link } %>
            </span>
            
            <span class="pull-right <%= 'visit-button' unless user_signed_in? %>">
            <%= link_to "Visit Site", link.url, 
                  class: "btn btn-default",
                  target: "_blank" %>
            </span>
          </div>
        </li>
        
        <li class="list-group-item link-description">
          <p class="lead">
            <%= link.description %>
          </p>
        </li>
          
        <li class="list-group-item link-user">
          <span>
            <strong>Submitted by:</strong><br>
            <%= link_to user_path(link.user) do %>
              <%= image_tag(link.user.profile_image.url(:micro)) %><br>
              <%= link.user.username %>
            <% end %>
          </span>
          
          <span class="pull-right">
            <%= social_share_button_tag(link.title, url: link.url) %>
          </span>
        </li>
          
      </ul>
      
    </div>
      
  </div>
</div>

app/views/links/partials/_show_approvers.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal"
       aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Approvers for this link</h4>
    </div>
    
    <div class="modal-body">
      <% if @approvers.any? %>
        <% @approvers.each do |user| %>
          <span class="approver-user">
            <%= link_to user_path(user) do %>
              <%= image_tag(user.profile_image.url(:micro)) %><br>
              <%= user.username %>
            <% end %>
          </span>
        <% end %>
      <% else %>
        <strong>No approvers yet. If you like this link then approve it :)
          <% unless user_signed_in? %>
            Log in or sign-up to enjoy Linkashare more.
          <% end %>
        </strong>
      <% end %>
    </div>
    
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <!--<button type="button" class="btn btn-primary">Save changes</button>-->
    </div>
    
  </div>
</div>