config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :links do
    collection do
      get 'my-links', to: "links#my_links", as: :my
      get 'my-approved-links', to: "links#my_approved_links",
          as: :my_approved
    end
    
    member do
      post 'approve-link', to: "links#approve_link", as: "approve"
      delete 'unapprove-link', to: "links#unapprove_link", as: "unapprove"
      get 'show-approvers', to: "links#show_approvers", as: "show_approvers"
    end
    
    resources :comments, only: [:create, :destroy]
  end
  
  resources :user, only: [:show] do
    member do
      get 'submitted-links', to: "user#submitted_links", as: "submitted_links"
      get 'approved-links', to: "user#approved_links", as: "approved_links"
    end
  end
  
  root to: "links#index"
  
  get 'about' => 'pages#about', as: :about
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  
  validates_presence_of :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    respond_to do |format|
      format.js do
        @link = Link.find(params[:link_id])
        @comment = @link.comments.create(content: comment_params[:content],
                   user: current_user)
        if @comment.errors.any?
          render 'create_error'  # create_error.js.erb
        end
        
        # create.js.erb
      end
    end
  end
  
  def destroy
    respond_to do |format|
      format.js do
        @link = Link.find(params[:link_id])
        @comment = @link.comments.find(params[:id])
        @comment.destroy
        
        @comments = @link.comments
        # destroy.js.erb
      end
    end
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:content)  
  end
end

app/views/comments/partials/_comment.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to user_path(comment.user) do %>
      <%= image_tag(comment.user.profile_image.url(:micro),
          class: "media-object") %>
    <% end %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= comment.user.username %></h4>
    <%= comment.content %>
    <% if can?(:destroy, comment) %>
      <div class="delete-comment-btn">
        <%= link_to "Delete Comment", link_comment_path(comment.link, comment),
            method: :delete, remote: true, class: "btn btn-danger btn-xs",
            data: { confirm: "Delete this comment?" } %>
      </div>    
    <% end %>
  </div>
</div>

app/views/comments/partials/_comment_form.html.erb
<%= form_for([link, link.comments.build], remote: true) do |f| %>
  <% if @comment && @comment.errors.any? %>
    <div id="comment-errors">
      <% @comment.errors.full_messages.each do |message| %>
        <h5 class="text-danger"><strong><%= message %></strong></h5>
      <% end %>
    </div>
  <% end %>

  <%= f.label :content, "Add Comment" %><br>
  <%= f.text_area :content, size: "30x5" %><br>
  <%= f.submit "Submit Comment", class: "btn btn-success btn-sm" %>
<% end %>