config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :links do
    collection do
      get 'my-links', to: "links#my_links", as: :my
      get 'my-approved-links', to: "links#my_approved_links",
          as: :my_approved
    end
    
    member do
      post 'approve-link', to: "links#approve_link", as: "approve"
      delete 'unapprove-link', to: "links#unapprove_link", as: "unapprove"
      get 'show-approvers', to: "links#show_approvers", as: "show_approvers"
    end
    
    resources :comments, only: [:create, :destroy]
  end
  
  resources :user, only: [:show] do
    member do
      get 'submitted-links', to: "user#submitted_links", as: "submitted_links"
      get 'approved-links', to: "user#approved_links", as: "approved_links"
    end
  end
  
  root to: "links#index"
  
  get 'about' => 'pages#about', as: :about
end

app/models/link.rb
class Link < ApplicationRecord
  has_attached_file :website_image,
    styles: { medium: "200x200#", thumb: "100x100#" },
    storage: :cloudinary,
    default_url: "/images/missing.png",
    path: ":id/:style/:filename",
    cloudinary_upload_options: {
      default: { tags: "web_images" }
    }

      
  # Validations
  validates_attachment_content_type :website_image, content_type: /\Aimage\/.*\z/
  validates :url, uniqueness: true
  validates_presence_of :url, :title, :description
  
  # Associations
  belongs_to :user
  
  has_many :approvals
  has_many :approvers, through: :approvals, dependent: :destroy
  
  has_many :comments, dependent: :destroy
  
  
  def get_link_data(url)
    url = format_url_correctly(url)
    if Link.where(url: url).any?
      self.errors.add(:url, "Link already exists.")
      return false  
    end
    
    begin
      return LinkThumbnailer.generate(url)
    rescue
      self.errors.add(:url, "Unable to reach link.")
      return false
    end
    
    url
  end
  
  def fetch_website_image(link_data)
    unless link_data.images.empty?
      begin
        image_url = link_data.images.first.src.to_s
        image_url = remove_query_string(image_url)
        image = open(image_url)
        filename = image.base_uri.to_s.split('/')[-1]
        image_path = Rails.root.join('tmp', filename)   
        IO.copy_stream(image, image_path)
        File.open(image_path, 'rb') do |file|
          self.website_image = file
        end
      rescue OpenURI::HTTPError
        logger.debug "Error fetching #{image_url} OpenURI::HTTPError"
      rescue
        logger.debug "Error fetching #{image_url}"
      end
    end
  end
  
  private
  
  def format_url_correctly(url)
    self.url = url
    unless self.url[/\Ahttp:\/\//] || self.url[/\Ahttps:\/\//]
      self.url = "http://#{self.url}"
    end
    
    self.url
  end
  
  def remove_query_string(url)
    url.split('?').first
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :show_approvers]
  before_action :find_link, only: [:show, :edit, :update, :destroy,
    :approve_link, :unapprove_link, :show_approvers]
  before_action :set_ransack_search_object
  
  authorize_resource
  skip_authorize_resource only: [:my_links, :my_approved_links,
                                 :approve_link, :unapprove_link,
                                 :show_approvers]
  
  LinksPerPage = 10
    
  def index
    if params[:search_btn]
      @links = @q.result(distinct: true).order(created_at: :desc)
                 .paginate(:page => params[:page], :per_page => LinksPerPage)
    else
      @links = Link.order(created_at: :desc)
                   .paginate(:page => params[:page], :per_page => LinksPerPage)
    end
  end
  
  def my_links
    @links = Link.where(user: current_user).order(created_at: :desc)
                 .paginate(:page => params[:page], :per_page => LinksPerPage)
    render 'index'
  end
  
  def my_approved_links
    @links = current_user.approved_links.order(created_at: :desc)
                 .paginate(:page => params[:page], :per_page => LinksPerPage)
    render 'index'
  end
  
  def new
    @link = Link.new
  end
  
  def create
    respond_to do |format|
      format.js do
        @link = Link.new
        
        link_data = @link.get_link_data(link_params[:url])
        unless link_data
          render 'url_error' and return  # url_error.js.erb
        end
        @link.url = link_data.url
        
        if params[:fetch_url]  # first step: fetch url data
          @link.title = link_data.title
          @link.description = link_data.description
        elsif params[:add_link]  # second step: actual record creation
          @link.fetch_website_image(link_data)
          @link.title = link_params[:title]
          @link.description = link_params[:description]
          @link.user = current_user
          
          # image spoofing detection workaround
          # just set website_image_file_name to false
          if @link.errors[:website_image].first =~
             /has contents that are not what they are reported to be/
            @link.website_image_file_name = false
          end
          
          if @link.save
            redirect_to @link
          else
            render 'create' # create.js.erb
          end
        end
        
      end # format
    end # respont_to
  end
  
  def show
    @comments = @link.comments.includes(:user)
  end
  
  def approve_link
    respond_to do |format|
      format.js do
        begin 
          @link.approvers << current_user
        ensure
          render 'approve_link'
        end
      end
    end
  end
  
  def unapprove_link
    respond_to do |format|
      format.js do
        begin
          @link.approvers.delete(current_user)
        ensure
          render 'approve_link'
        end
      end
    end
  end
  
  def show_approvers
    respond_to do |format|
      format.js do
        @approvers = @link.approvers
        
        # render show_approvers.js.erb
      end
    end
  end
  
  def edit
  end
  
  def update
    if @link.update(title: link_params[:title], 
         description: link_params[:description])
      redirect_to @link
    else
      render 'show'
    end
  end
  
  def destroy
    @link.destroy
    redirect_to root_path
  end
  
  private
  
  def set_ransack_search_object
    @q = Link.ransack(params[:q])
  end
  
  def find_link
    @link = Link.find(params[:id])
  end
  
  def link_params
    params.require(:link).permit(:url, :title, :description, :website_image)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_link.html.erb
<div class="row">
  <div class="col-sm-8">
    <h2><%= link.title %></h2>
    
    <p>
    <%= image_tag(link.website_image.url(:medium)) %>   
    </p>
    
    <p id="link-approval">
      <%= render partial: 'links/partials/approve_link', 
                 locals: { link: link } %>
    </p>
    
    <p>
    <%= link_to "Visit Site", link.url, class: "btn btn-success",
          target: "_blank" %>
    </p>
  
    <p class="lead">
    <%= link.description %>
    </p>
    
    <p>
      <strong>Submitted by:</strong><br>
      <%= link_to user_path(link.user) do %>
        <%= image_tag(link.user.profile_image.url(:micro)) %><br>
        <%= link.user.username %>
      <% end %>
    </p>
  </div>
</div>

app/views/links/approve_link.js.erb
$("#link-approval")
  .html("<%= j(render partial: 'links/partials/approve_link', locals: { link: @link }) %>");

app/views/links/create.js.erb
$("#create-link-form").html("<%= j(render 'links/partials/create_form_plus') %>");

app/views/links/edit.html.erb
<% content_for(:title) do %>
  Edit Link
<% end %>

<div class="container links-main">
  <h3>Update Link Details</h3>
  
  <div class="col-sm-offset-1">
    <p>
      <%= image_tag(@link.website_image.url(:medium)) %>   
    </p>
    
    <p>
      <%= link_to "Visit Site", @link.url, class: "btn btn-sm btn-default",
          target: "_blank" %>
    </p>
  </div>
    
  <%= form_for(@link, html: { class: "form-horizontal" }) do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "control-label col-sm-1" %>
      <div class="col-sm-6">
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
        
    <div class="form-group">
      <%= f.label :description, class: "control-label col-sm-1" %>
      <div class="col-sm-6">
        <%= f.text_area :description, size: "10x5", class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-6">
        <%= f.submit "Update Link Details", class: "btn btn-success",
            data: { disable_with: "Updating Link..." } %>
            
        <%= link_to "Cancel", @link, 
            class: "btn btn-default button-left-margin",
            data: { disable_with: "Back to Link..." } %>
      </div>
    </div>
  <% end %>
</div>

app/views/links/index.html.erb
<% content_for(:title) do %>
 <%= get_index_title %>
<% end %>

<div class="container links-main">
  <div class="row">
    <div class="col-sm-8 col-xs-12">
      <% if @links.any? %>
        <% @links.each do |link| %>
          <div class="link-item">
            <h2><%= link_to link.title, link %></h2>
            
            <p>
              <%= link_to link do %>  
                <%= image_tag(link.website_image.url(:thumb),
                              size: "100x100") %>   
              <% end %>
            </p>
            
            <p class="lead">
            <%= link.description %>
            </p>
          </div>
          <hr>
        <% end %>
        
        <div class="linka_pagination">
          <%= will_paginate @links %>
        </div>
      <% else %>  
        <h2>No links to be shown.</h2>
        <% if can?(:create, Link) %>
          Try adding one:
          <%= link_to new_link_text, new_link_path, class: "btn btn-success" %>
        <% end %>
      <% end %>
    </div> <!-- links -->
    
  </div> <!-- row -->
</div>

app/views/links/new.html.erb
<% content_for(:title) do %>
  New Link
<% end %>

<div class="container links-main">
  <h1 class="link-header">New Link</h1>    
    
  <div id="create-link-form">
    <%= form_for(@link, remote: true, html: { class: "form-horizontal" }) do |f| %>
      <div class="form-group">
        <%= f.label :url, class: "control-label col-sm-1", for: "link_url" %>
        <div class="col-sm-6">
          <%= f.text_field :url, class: "form-control" %>
        </div>
      </div>
      
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-6">
          <%= f.button "Fetch Url", class: "btn btn-primary",
                name: "fetch_url", 
                data: { disable_with: fetching_url_text } %>
        </div>
      </div>
      
      <div id="create-link-errors"></div>
      
    <% end %>
    
  </div>  
</div>

app/views/links/show.html.erb
<% content_for(:title) do %>
  <%= (@link ? @link.title : "Link") %>
<% end %>

<div class="container links-main">
  <%= render partial: 'links/partials/link', locals: { link: @link } %>
  
  <% if can?(:update, @link) %>
    <%= link_to "Edit Link", edit_link_path(@link),
        class: "btn btn-primary" %>
  <% end %>
  <% if can?(:destroy, @link) %>
    <%= link_to "Delete Link", link_path(@link), method: :delete,
        data: { confirm: "Are you sure you want to delete this link?" },
        class: "btn btn-danger button-left-margin" %>
  <% end %>
  
  <div class="row">
    <div id="link-comments" class="col-sm-8">
      <div id="comments-list">
        <h3>
          <%= pluralize(@comments.size, "Comment") %>
        </h3>
        <%= render partial: 'comments/partials/comment', 
            collection: @comments  %>
      </div>
      
      <% if can?(:create, Comment) %>
        <div id="comment-form">
          <%= render partial: 'comments/partials/comment_form',
              locals: { link: @link } %>
        </div>
      <% end %>
    </div>
  </div>
  
</div>

app/views/links/show_approvers.js.erb
$("#approvers-modal").html("<%= j(render 'links/partials/show_approvers') %>");
$("#approvers-modal").modal('show');

app/views/links/url_error.js.erb
$("#create-link-errors").html("<%= j(render 'links/partials/create_url_errors') %>");