config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :links do
    collection do
      get 'my-links', to: "links#my_links", as: :my
      get 'my-approved-links', to: "links#my_approved_links",
          as: :my_approved
    end
    
    member do
      post 'approve-link', to: "links#approve_link", as: "approve"
      delete 'unapprove-link', to: "links#unapprove_link", as: "unapprove"
      get 'show-approvers', to: "links#show_approvers", as: "show_approvers"
    end
    
    resources :comments, only: [:create, :destroy]
  end
  
  resources :user, only: [:show] do
    member do
      get 'submitted-links', to: "user#submitted_links", as: "submitted_links"
      get 'approved-links', to: "user#approved_links", as: "approved_links"
    end
  end
  
  root to: "links#index"
  
  get 'about' => 'pages#about', as: :about
end

app/views/layouts/_flash_messages.html.erb
<p class="notice text-primary"><strong><%= notice %></strong></p>
<p class="alert text-danger"><strong><%= alert %></strong></p>  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top role="navigation">
     <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" 
           data-toggle="collapse" 
           data-target=".navbar-collapse">
          <span class="sr-only">Toggle Navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <span class="glyphicon glyphicon-link"></span> Linkashare
        <% end %>
      </div>
      
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(root_path) %>">
            <%= link_to "Links", root_path %>
          </li>
          <li class="<%= 'active' if current_page?(about_path) %>">
            <%= link_to "About", about_path %>
          </li>
        </ul>
        
        <% if user_signed_in? %>
          <span class="navbar-right">
            <div class="btn-group">
              <button id="links-btn" type="button" 
                class="btn btn-primary dropdown-toggle" 
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Links <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <% if can?(:create, Link) %>
                  <li><%= link_to new_link_text, new_link_path %></li>
                <% end %>
                <li><%= link_to my_links_text, my_links_path %></li>
                <li><%= link_to approved_links_text, 
                          my_approved_links_path %></li>
              </ul>
            </div>
            
            <div class="btn-group navbtn-top">
              <button id="user-btn" type="button" 
                class="btn btn-primary dropdown-toggle" 
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %> <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to view_profile_text, user_path(current_user.slug) %>
                </li>
                <li>
                  <%= link_to edit_settings_text, edit_user_registration_path %>
                </li>
              </ul>
            </div>
            
            
            <%= link_to logout_text, destroy_user_session_path, method: :delete,
                  class: "btn btn-primary navbar-btn navbtn-top" %>
          </span>
        <% else %>
          <span class="navbar-right">
            <%= link_to login_text, new_user_session_path, 
                        class: "btn btn-primary navbar-btn" %>
            <%= link_to sign_up_text, new_user_registration_path,
                        class: "btn btn-success navbar-btn navbtn-top" %>
          </span>
        <% end %>
        
        <% if search_visible? %>
          <%= search_form_for(@q, url: links_path, 
                              class: "navbar-form navbar-right") do |f| %>
            <div class="form-group">
              <%= f.search_field :title_or_description_cont,
                  class: "form-control" %>
            </div>
            
            <%= f.button search_text, class: "btn btn-primary", 
                name: "search_btn", id: "search-btn",
                data: { disable_with: searching_text } %>
          <% end %>
        <% end %>
      
    </div> <!-- Navbar Elements -->
 </div> <!-- Container -->
</nav> <!-- Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkashare - <%= content_for?(:title) ? yield(:title) : "discover the web" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>   
       
    <%= yield %>
  </body>
</html>